name: sofi_interview
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_hooks: ^0.19.0
  flutter_inappwebview: ^5.7.2+3
  flutter_test:
    sdk: flutter
  form_validator: ^2.1.1
  get: ^4.6.5
  mocktail: ^0.3.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/